import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#08111f',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#08111f',
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#08111f',
    paddingHorizontal: 20,
    paddingVertical: 28,
    gap: 18,
  },
  feedScreen: {
    flex: 1,
    backgroundColor: '#08111f',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 8,
  },
  feedHeader: {
    gap: 4,
    position: 'relative',
  },
  eyebrow: {
    color: '#f97316',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  title: {
    color: '#f8fafc',
    fontSize: 40,
    fontWeight: '800',
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: '#0f172a',
    borderColor: '#1e293b',
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 14,
  },
  sessionStrip: {
    backgroundColor: 'rgba(8, 16, 24, 0.88)',
    borderColor: 'rgba(148, 163, 184, 0.18)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  input: {
    backgroundColor: '#111827',
    borderColor: '#334155',
    borderRadius: 16,
    borderWidth: 1,
    color: '#f8fafc',
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#f97316',
    borderRadius: 14,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#fff7ed',
    fontSize: 15,
    fontWeight: '800',
  },
  warningCard: {
    backgroundColor: '#3f1d16',
    borderColor: '#fb923c',
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    gap: 8,
  },
  warningTitle: {
    color: '#ffedd5',
    fontSize: 16,
    fontWeight: '800',
  },
  warningText: {
    color: '#fed7aa',
    fontSize: 14,
    lineHeight: 20,
  },
  loadingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  accountTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  accountActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  accountSlimMeta: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  accountTag: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '800',
  },
  accountDot: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '800',
  },
  balanceBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  balanceBadgeAlert: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
  },
  accountBalance: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '700',
  },
  accountBalanceAlert: {
    color: '#fca5a5',
  },
  topBarPill: {
    backgroundColor: 'rgba(30, 41, 59, 0.7)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  topBarPillActive: {
    backgroundColor: 'rgba(249, 115, 22, 0.22)',
  },
  topBarPillText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  inlineLogoutButton: {
    backgroundColor: 'rgba(30, 41, 59, 0.7)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  inlineLogoutText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  textLink: {
    color: '#f97316',
    fontSize: 14,
    fontWeight: '700',
  },
  swipeIndicator: {
    color: '#d1fae5',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  swiper: {
    flex: 1,
  },
  swiperContent: {
    paddingBottom: 8,
  },
  betSlide: {
    paddingVertical: 4,
  },
  betSlideInner: {
    flex: 1,
    borderRadius: 28,
    overflow: 'hidden',
    justifyContent: 'space-between',
    padding: 22,
  },
  betSlideBack: {
    backgroundColor: '#0f3d2e',
  },
  betSlideLay: {
    backgroundColor: '#4a1622',
  },
  betSlideDual: {
    backgroundColor: '#142235',
  },
  betHeroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  betHeroIndex: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
  },
  betHeroMarket: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  betHeroBody: {
    flex: 1,
    justifyContent: 'center',
    gap: 10,
  },
  betHeroMatch: {
    color: '#cbd5e1',
    fontSize: 18,
    fontWeight: '700',
  },
  betHeroTitle: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: '900',
    letterSpacing: 0.4,
    lineHeight: 44,
  },
  betHeroLabel: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  betHeroHint: {
    color: '#dbeafe',
    fontSize: 15,
    lineHeight: 22,
    maxWidth: '85%',
  },
  betActionPanel: {
    backgroundColor: 'rgba(8, 15, 23, 0.62)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  betActionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  betActionHeaderRight: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  betActionTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '800',
  },
  helpButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  helpButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 10,
  },
  choiceButton: {
    borderRadius: 18,
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  choiceButtonBack: {
    backgroundColor: 'rgba(34, 197, 94, 0.18)',
  },
  choiceButtonLay: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
  },
  choiceButtonActive: {
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
  },
  choiceButtonLabel: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  choiceButtonValue: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
  },
  returnGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  returnCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  returnLabel: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  returnValue: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
  },
  settlementNote: {
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 18,
  },
  actionButtonRow: {
    gap: 12,
  },
  actionBetButton: {
    borderRadius: 18,
    gap: 8,
    overflow: 'visible',
    paddingHorizontal: 16,
    paddingVertical: 16,
    position: 'relative',
  },
  actionBetButtonBack: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
    borderColor: 'rgba(34, 197, 94, 0.45)',
    borderWidth: 1,
  },
  actionBetButtonLay: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: 'rgba(239, 68, 68, 0.45)',
    borderWidth: 1,
  },
  actionBetTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionBetSide: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  actionBetOdds: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
  },
  actionBetLabel: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  actionBetMeta: {
    color: '#dbeafe',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  actionBetCta: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  buttonBurst: {
    bottom: 18,
    left: '50%',
    position: 'absolute',
    pointerEvents: 'none',
    top: 18,
    width: 1,
    zIndex: 2,
  },
  buttonBurstParticle: {
    borderRadius: 999,
    height: 10,
    left: -5,
    position: 'absolute',
    top: '50%',
    width: 10,
  },
  betAmountInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 16,
    borderWidth: 1,
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '800',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chipText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  placeBetButton: {
    alignItems: 'center',
    borderRadius: 18,
    paddingVertical: 16,
  },
  placeBetButtonBack: {
    backgroundColor: '#22c55e',
  },
  placeBetButtonLay: {
    backgroundColor: '#ef4444',
  },
  placeBetButtonText: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  betSideBadge: {
    borderRadius: 999,
    minWidth: 72,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  betSideBack: {
    backgroundColor: '#166534',
  },
  betSideLay: {
    backgroundColor: '#991b1b',
  },
  betSideBadgeText: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  betSlipsPopover: {
    position: 'absolute',
    right: 0,
    top: 52,
    zIndex: 10,
    width: '100%',
  },
  betSlipsCard: {
    backgroundColor: '#0f172a',
    borderColor: 'rgba(148, 163, 184, 0.14)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  betSlipsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  betSlipsTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '800',
  },
  betSlipsCount: {
    color: '#d1fae5',
    fontSize: 13,
    fontWeight: '800',
  },
  betSlipsEmpty: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
  },
  betSlipsList: {
    maxHeight: 180,
  },
  betSlipItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 16,
    gap: 4,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  betSlipTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  betSlipTitle: {
    color: '#f8fafc',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
  },
  betSlipAmount: {
    color: '#f97316',
    fontSize: 14,
    fontWeight: '900',
  },
  betSlipMeta: {
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 18,
  },
});
