import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#120e0d',
  },
  gameScreen: {
    flex: 1,
    padding: 10,
  },
  topHud: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    left: 14,
    position: 'absolute',
    right: 14,
    top: 12,
    zIndex: 5,
  },
  topHudBadge: {
    backgroundColor: 'rgba(16, 12, 10, 0.82)',
    borderColor: 'rgba(227, 185, 126, 0.52)',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  topHudLabel: {
    color: '#d4bb8f',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  topHudValue: {
    color: '#fff4dd',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 2,
  },
  topHudLogout: {
    backgroundColor: 'rgba(113, 36, 30, 0.9)',
    borderColor: 'rgba(229, 153, 126, 0.52)',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  topHudLogoutText: {
    color: '#fff0e4',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  tableShell: {
    flex: 1,
    position: 'relative',
  },
  tableGlow: {
    backgroundColor: 'rgba(23, 181, 122, 0.18)',
    borderRadius: 220,
    bottom: 18,
    left: 18,
    position: 'absolute',
    right: 18,
    top: 18,
  },
  tableFelt: {
    alignItems: 'center',
    backgroundColor: '#0c5a43',
    borderColor: '#835c33',
    borderRadius: 38,
    borderWidth: 10,
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  tableRail: {
    borderColor: 'rgba(255, 243, 214, 0.14)',
    borderRadius: 30,
    borderWidth: 1,
    bottom: 10,
    left: 10,
    position: 'absolute',
    right: 10,
    top: 10,
  },
  tableInnerRing: {
    borderColor: 'rgba(255, 243, 214, 0.1)',
    borderRadius: 999,
    borderWidth: 1,
    height: 200,
    position: 'absolute',
    top: '33%',
    width: 200,
  },
  lifeTrack: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 6,
  },
  lifePip: {
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  lifePipPlayer: {
    backgroundColor: '#f4b942',
  },
  lifePipAi: {
    backgroundColor: '#ff6b57',
  },
  lifePipEmpty: {
    backgroundColor: '#473733',
  },
  aiTopSeat: {
    alignItems: 'center',
    position: 'absolute',
    top: 68,
  },
  aiLeftSeat: {
    alignItems: 'center',
    left: 20,
    position: 'absolute',
    top: '38%',
  },
  aiRightSeat: {
    alignItems: 'center',
    position: 'absolute',
    right: 20,
    top: '38%',
  },
  playerSeat: {
    alignItems: 'center',
    bottom: 92,
    position: 'absolute',
  },
  seatLabel: {
    color: '#f5eddc',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  centerArena: {
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: '38%',
    zIndex: 1,
  },
  coinStack: {
    alignItems: 'center',
    height: 86,
    justifyContent: 'flex-end',
    marginBottom: -20,
    width: 120,
  },
  coin: {
    borderColor: '#8f5f13',
    borderRadius: 999,
    borderWidth: 2,
    height: 18,
    position: 'absolute',
    width: 64,
  },
  coinWarm: {
    backgroundColor: '#e4a72a',
  },
  coinBright: {
    backgroundColor: '#f8cc56',
  },
  betTrailCoin: {
    backgroundColor: '#f4c750',
    borderColor: '#8f5f13',
    borderRadius: 999,
    borderWidth: 2,
    height: 18,
    left: '50%',
    marginLeft: -32,
    marginTop: -9,
    position: 'absolute',
    top: '43%',
    width: 64,
    zIndex: 3,
  },
  centerPot: {
    alignItems: 'center',
    backgroundColor: '#1a1612',
    borderColor: '#d0a65f',
    borderRadius: 999,
    borderWidth: 3,
    height: 120,
    justifyContent: 'center',
    width: 120,
  },
  centerPotLabel: {
    color: '#d9bd88',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  centerPotValue: {
    color: '#fff7e8',
    fontSize: 40,
    fontWeight: '900',
    lineHeight: 42,
    marginTop: 2,
  },
  centerPotTurn: {
    color: '#97e4c1',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  gameCard: {
    borderRadius: 18,
    height: 118,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: 88,
  },
  gameCardFront: {
    backgroundColor: '#f7efdf',
    borderColor: '#d5b37a',
    borderWidth: 2,
  },
  gameCardBack: {
    backgroundColor: '#6a261f',
    borderColor: '#e1b989',
    borderWidth: 2,
  },
  gameCardCorner: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  gameCardCenter: {
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  gameCardValue: {
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  gameCardFrontText: {
    color: '#29160f',
  },
  gameCardFrontSubtext: {
    color: '#815d38',
  },
  gameCardBackText: {
    color: '#fff1dc',
  },
  authOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(8, 8, 8, 0.6)',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 9,
  },
  authPanel: {
    backgroundColor: '#1a1512',
    borderColor: '#c99857',
    borderRadius: 28,
    borderWidth: 2,
    maxWidth: 380,
    paddingHorizontal: 20,
    paddingVertical: 22,
    width: '88%',
  },
  authEyebrow: {
    color: '#cfb17f',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  authTitle: {
    color: '#fff4df',
    fontSize: 28,
    fontWeight: '900',
    marginTop: 8,
  },
  authBody: {
    color: '#cdbda0',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  authSwitchRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  authGhostAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#2f291f',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  authGhostActionText: {
    color: '#f0c977',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  authSwitch: {
    backgroundColor: '#2a221d',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  authSwitchActive: {
    backgroundColor: '#f2b43c',
  },
  authSwitchText: {
    color: '#d5cab6',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  authSwitchTextActive: {
    color: '#2d1701',
  },
  authFieldGroup: {
    marginTop: 16,
  },
  authFieldLabel: {
    color: '#e1d4bc',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  authInput: {
    backgroundColor: '#f3e6cf',
    borderRadius: 16,
    color: '#25150f',
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  authError: {
    color: '#ff9f8d',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 14,
  },
  authSubmit: {
    alignItems: 'center',
    backgroundColor: '#d14d35',
    borderRadius: 999,
    marginTop: 18,
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  authSubmitText: {
    color: '#fff2e6',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  actionBar: {
    alignItems: 'center',
    bottom: 18,
    gap: 10,
    left: 20,
    position: 'absolute',
    right: 20,
  },
  raiseRow: {
    flexDirection: 'row',
    gap: 8,
  },
  raiseChip: {
    alignItems: 'center',
    backgroundColor: '#f2b43c',
    borderRadius: 999,
    minWidth: 58,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  raiseChipValue: {
    color: '#2d1701',
    fontSize: 20,
    fontWeight: '900',
  },
  coyoteButton: {
    alignItems: 'center',
    backgroundColor: '#d14d35',
    borderRadius: 999,
    minWidth: 220,
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  coyoteButtonText: {
    color: '#fff2e6',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  nextRoundBarButton: {
    alignItems: 'center',
    backgroundColor: '#f2b43c',
    borderRadius: 999,
    minWidth: 240,
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  nextRoundBarButtonText: {
    color: '#2d1701',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  disabledAction: {
    opacity: 0.35,
  },
});
