import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#07111d',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#07111d',
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: '#07111d',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 24,
    gap: 16,
  },
  feedScreen: {
    flex: 1,
    backgroundColor: '#08111f',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 8,
  },
  feedHeader: {
    gap: 4,
    position: 'relative',
  },
  eyebrow: {
    color: '#f97316',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  title: {
    color: '#f8fafc',
    fontSize: 40,
    fontWeight: '800',
  },
  heroShell: {
    minHeight: '100%',
    justifyContent: 'center',
    position: 'relative',
  },
  heroGlowPrimary: {
    backgroundColor: 'rgba(0, 224, 176, 0.16)',
    borderRadius: 999,
    height: 240,
    position: 'absolute',
    right: -70,
    top: 10,
    width: 240,
  },
  heroGlowSecondary: {
    backgroundColor: 'rgba(255, 209, 102, 0.14)',
    borderRadius: 999,
    bottom: 36,
    height: 200,
    left: -60,
    position: 'absolute',
    width: 200,
  },
  heroCard: {
    backgroundColor: '#0c1827',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 32,
    borderWidth: 1,
    gap: 18,
    overflow: 'hidden',
    padding: 22,
    position: 'relative',
  },
  heroBadgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroBadge: {
    backgroundColor: '#d7ff64',
    borderRadius: 999,
    color: '#0f172a',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 7,
    textTransform: 'uppercase',
  },
  heroBadgeMuted: {
    color: '#9fb0c9',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  heroCopyBlock: {
    gap: 10,
  },
  heroTitle: {
    color: '#f8fafc',
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: -1,
    lineHeight: 44,
  },
  heroSubtitle: {
    color: '#b9c7dd',
    fontSize: 16,
    lineHeight: 24,
  },
  heroStatRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroStatChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    borderWidth: 1,
    minWidth: 94,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  heroStatValue: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '900',
  },
  heroStatLabel: {
    color: '#8ba0bf',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  heroFormCard: {
    backgroundColor: '#f3efe4',
    borderRadius: 26,
    gap: 12,
    padding: 18,
  },
  heroFormTitle: {
    color: '#142235',
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 2,
  },
  heroInput: {
    backgroundColor: '#fffdf8',
    borderColor: '#d4d0c4',
    borderRadius: 18,
    borderWidth: 1,
    color: '#142235',
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 15,
  },
  heroPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#142235',
    borderRadius: 18,
    paddingVertical: 15,
  },
  heroPrimaryButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  heroLinkRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    justifyContent: 'space-between',
    marginTop: 4,
  },
  heroTextLink: {
    color: '#0f766e',
    fontSize: 14,
    fontWeight: '800',
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: '#0f172a',
    borderColor: '#1e293b',
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 14,
  },
  sessionStrip: {
    backgroundColor: 'rgba(8, 16, 24, 0.88)',
    borderColor: 'rgba(148, 163, 184, 0.18)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  input: {
    backgroundColor: '#111827',
    borderColor: '#334155',
    borderRadius: 16,
    borderWidth: 1,
    color: '#f8fafc',
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#f97316',
    borderRadius: 14,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#fff7ed',
    fontSize: 15,
    fontWeight: '800',
  },
  warningCard: {
    backgroundColor: '#3f1d16',
    borderColor: '#fb923c',
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    gap: 8,
  },
  warningTitle: {
    color: '#ffedd5',
    fontSize: 16,
    fontWeight: '800',
  },
  warningText: {
    color: '#fed7aa',
    fontSize: 14,
    lineHeight: 20,
  },
  loadingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  accountTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  accountActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  accountSlimMeta: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  accountTag: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '800',
  },
  accountDot: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '800',
  },
  balanceBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  balanceBadgeAlert: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
  },
  accountBalance: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '700',
  },
  accountBalanceAlert: {
    color: '#fca5a5',
  },
  topBarPill: {
    backgroundColor: 'rgba(30, 41, 59, 0.7)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  topBarPillActive: {
    backgroundColor: 'rgba(249, 115, 22, 0.22)',
  },
  topBarPillText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  inlineLogoutButton: {
    backgroundColor: 'rgba(30, 41, 59, 0.7)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  inlineLogoutText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  textLink: {
    color: '#f97316',
    fontSize: 14,
    fontWeight: '700',
  },
  swipeIndicator: {
    color: '#d1fae5',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  swiper: {
    flex: 1,
  },
  swiperContent: {
    paddingBottom: 8,
  },
  betSlide: {
    paddingVertical: 4,
  },
  betSlideInner: {
    flex: 1,
    borderRadius: 28,
    overflow: 'hidden',
    justifyContent: 'space-between',
    padding: 22,
  },
  betSlideBack: {
    backgroundColor: '#0f3d2e',
  },
  betSlideLay: {
    backgroundColor: '#4a1622',
  },
  betSlideDual: {
    backgroundColor: '#142235',
  },
  betHeroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  betHeroIndex: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
  },
  betHeroMarket: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  betHeroBody: {
    flex: 1,
    justifyContent: 'center',
    gap: 10,
  },
  betHeroBodyCompact: {
    gap: 6,
    marginTop: 12,
  },
  betHeroMatch: {
    color: '#cbd5e1',
    fontSize: 18,
    fontWeight: '700',
  },
  betHeroTitle: {
    color: '#ffffff',
    fontSize: 40,
    fontWeight: '900',
    letterSpacing: 0.4,
    lineHeight: 44,
  },
  betHeroTitleCompact: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
  },
  betHeroLabel: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  betHeroHint: {
    color: '#dbeafe',
    fontSize: 15,
    lineHeight: 22,
    maxWidth: '85%',
  },
  betHeroHintFull: {
    color: '#dbeafe',
    fontSize: 14,
    lineHeight: 20,
  },
  betActionPanel: {
    backgroundColor: 'rgba(8, 15, 23, 0.62)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  betActionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  betActionHeaderRight: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  betActionTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '800',
  },
  helpButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  helpButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 10,
  },
  choiceButton: {
    borderRadius: 18,
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  choiceButtonBack: {
    backgroundColor: 'rgba(34, 197, 94, 0.18)',
  },
  choiceButtonLay: {
    backgroundColor: 'rgba(239, 68, 68, 0.18)',
  },
  choiceButtonActive: {
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
  },
  choiceButtonLabel: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  choiceButtonValue: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
  },
  returnGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  returnCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  returnLabel: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  returnValue: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
  },
  settlementNote: {
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 18,
  },
  ballOptionList: {
    maxHeight: 360,
  },
  ballOptionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    marginBottom: 10,
    padding: 12,
  },
  ballOptionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  ballOptionLabelWrap: {
    flex: 1,
    gap: 4,
  },
  ballOptionLabel: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
  },
  ballOptionMeta: {
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 18,
  },
  ballOptionButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  ballOptionButton: {
    borderRadius: 16,
    flex: 1,
    gap: 6,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 12,
    position: 'relative',
  },
  ballOptionButtonSide: {
    color: '#f8fafc',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  ballOptionButtonOdds: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  ballOptionButtonCta: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  ballOptionButtonMeta: {
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
  actionButtonRow: {
    gap: 12,
  },
  actionBetButton: {
    borderRadius: 18,
    gap: 8,
    overflow: 'visible',
    paddingHorizontal: 16,
    paddingVertical: 16,
    position: 'relative',
  },
  actionBetButtonBack: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
    borderColor: 'rgba(34, 197, 94, 0.45)',
    borderWidth: 1,
  },
  actionBetButtonLay: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: 'rgba(239, 68, 68, 0.45)',
    borderWidth: 1,
  },
  actionBetTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionBetSide: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  actionBetOdds: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
  },
  actionBetLabel: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  actionBetMeta: {
    color: '#dbeafe',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  actionBetCta: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  buttonBurst: {
    bottom: 18,
    left: '50%',
    position: 'absolute',
    pointerEvents: 'none',
    top: 18,
    width: 1,
    zIndex: 2,
  },
  buttonBurstParticle: {
    borderRadius: 999,
    height: 10,
    left: -5,
    position: 'absolute',
    top: '50%',
    width: 10,
  },
  betAmountInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 16,
    borderWidth: 1,
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '800',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chipText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  viewToggleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  viewTogglePill: {
    backgroundColor: 'rgba(30, 41, 59, 0.7)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  viewTogglePillActive: {
    backgroundColor: 'rgba(249, 115, 22, 0.24)',
  },
  viewToggleText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  marketBoard: {
    flex: 1,
  },
  marketBoardContent: {
    gap: 12,
    paddingBottom: 16,
  },
  marketBoardToolbarDense: {
    backgroundColor: '#102033',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 12,
  },
  marketBoardToolbarDenseCompact: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  marketBoardToolbarCopy: {
    flex: 1,
    gap: 4,
  },
  marketBoardToolbarMeta: {
    color: '#9fb0c9',
    fontSize: 12,
    lineHeight: 18,
  },
  marketBoardTitle: {
    color: '#f8fafc',
    fontSize: 20,
    fontWeight: '900',
  },
  marketBoardStakeInput: {
    minWidth: 110,
    paddingVertical: 10,
  },
  marketBoardSummaryBar: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  marketBoardSummaryBarCompact: {
    gap: 10,
  },
  marketBoardSummaryText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  marketBoardTableScrollContent: {
    paddingBottom: 4,
  },
  marketBoardTable: {
    minWidth: 720,
    width: '100%',
  },
  marketBoardTableCompact: {
    minWidth: 0,
  },
  marketBoardHeaderRow: {
    backgroundColor: '#16283d',
    borderRadius: 14,
    flexDirection: 'row',
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  marketBoardHeaderCell: {
    color: '#8ba0bf',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  marketBoardHeaderSelection: {
    flex: 1.7,
  },
  marketBoardHeaderPrice: {
    textAlign: 'center',
    width: 118,
  },
  marketBoardHeaderAction: {
    textAlign: 'right',
    width: 126,
  },
  marketBoardGroup: {
    backgroundColor: '#0f1c2c',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
  },
  marketBoardGroupBar: {
    alignItems: 'center',
    backgroundColor: '#13263a',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  marketBoardGroupBarCompact: {
    alignItems: 'flex-start',
    flexDirection: 'column',
    gap: 6,
  },
  teamLogoStack: {
    flexDirection: 'row',
    marginRight: 10,
  },
  teamLogoStackCompact: {
    marginRight: 0,
    marginBottom: 2,
  },
  teamLogoImage: {
    backgroundColor: '#ffffff',
    borderColor: 'rgba(255, 255, 255, 0.16)',
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    marginRight: -8,
    width: 28,
  },
  teamLogoImageCompact: {
    height: 24,
    width: 24,
  },
  teamLogoFallback: {
    alignItems: 'center',
    backgroundColor: '#203247',
    borderColor: 'rgba(255, 255, 255, 0.16)',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginRight: -8,
  },
  teamLogoFallbackText: {
    color: '#f8fafc',
    fontSize: 10,
    fontWeight: '900',
  },
  marketBoardGroupCopy: {
    flex: 1,
    gap: 3,
    marginRight: 12,
  },
  marketBoardGroupEyebrow: {
    color: '#f97316',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  marketBoardGroupTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
  },
  marketBoardGroupMatch: {
    color: '#b9c7dd',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
    width: 150,
  },
  marketBoardGroupMatchCompact: {
    textAlign: 'left',
    width: 'auto',
  },
  marketBoardGridRow: {
    alignItems: 'stretch',
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  marketBoardGridRowCompact: {
    flexWrap: 'wrap',
  },
  marketBoardSelectionCell: {
    flex: 1.7,
    justifyContent: 'center',
    paddingRight: 4,
  },
  marketBoardSelectionCellCompact: {
    flexBasis: '100%',
    paddingRight: 0,
  },
  marketBoardSelectionLabel: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
  },
  marketBoardSelectionMeta: {
    color: '#9fb0c9',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  marketBoardPriceCell: {
    alignItems: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 10,
    position: 'relative',
    width: 110,
  },
  marketBoardPriceCellCompact: {
    flex: 1,
    minWidth: 0,
    width: '48%',
  },
  marketBoardBackCell: {
    backgroundColor: 'rgba(59, 130, 246, 0.28)',
    borderColor: 'rgba(96, 165, 250, 0.42)',
    borderWidth: 1,
  },
  marketBoardLayCell: {
    backgroundColor: 'rgba(244, 114, 182, 0.24)',
    borderColor: 'rgba(244, 114, 182, 0.42)',
    borderWidth: 1,
  },
  marketBoardPriceOdds: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 28,
  },
  marketBoardPriceSub: {
    color: '#e2e8f0',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  marketBoardExecCell: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    width: 118,
  },
  marketBoardExecCellCompact: {
    alignItems: 'flex-start',
    width: '100%',
  },
  marketBoardExecTop: {
    color: '#f8fafc',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'right',
  },
  marketBoardExecBottom: {
    color: '#8ba0bf',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 4,
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  marketBoardSection: {
    gap: 12,
  },
  marketBoardSectionTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '900',
  },
  marketBoardExternalTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  marketBoardExternalCard: {
    backgroundColor: '#0f172a',
    borderColor: 'rgba(148, 163, 184, 0.16)',
    borderRadius: 20,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  marketBoardExternalTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  marketBoardExternalMeta: {
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 18,
  },
  marketBoardExternalBookmaker: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 16,
    gap: 8,
    padding: 12,
  },
  marketBoardExternalBookmakerTitle: {
    color: '#f97316',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  marketBoardExternalMarket: {
    gap: 6,
  },
  marketBoardExternalMarketKey: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  marketBoardExternalOutcomeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  marketBoardExternalOutcomeName: {
    color: '#f8fafc',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  marketBoardExternalOutcomePrice: {
    color: '#34d399',
    fontSize: 13,
    fontWeight: '900',
  },
  placeBetButton: {
    alignItems: 'center',
    borderRadius: 18,
    paddingVertical: 16,
  },
  placeBetButtonBack: {
    backgroundColor: '#22c55e',
  },
  placeBetButtonLay: {
    backgroundColor: '#ef4444',
  },
  placeBetButtonText: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  betSideBadge: {
    borderRadius: 999,
    minWidth: 72,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  betSideBack: {
    backgroundColor: '#166534',
  },
  betSideLay: {
    backgroundColor: '#991b1b',
  },
  betSideBadgeText: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  betSlipsPopover: {
    position: 'absolute',
    right: 0,
    top: 52,
    zIndex: 10,
    width: '100%',
  },
  betSlipsCard: {
    backgroundColor: '#0f172a',
    borderColor: 'rgba(148, 163, 184, 0.14)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  betSlipsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  betSlipsTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '800',
  },
  betSlipsCount: {
    color: '#d1fae5',
    fontSize: 13,
    fontWeight: '800',
  },
  betSlipsEmpty: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
  },
  betSlipsList: {
    maxHeight: 180,
  },
  betSlipItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 16,
    gap: 4,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  betSlipTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  betSlipTitle: {
    color: '#f8fafc',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
  },
  betSlipAmount: {
    color: '#f97316',
    fontSize: 14,
    fontWeight: '900',
  },
  betSlipMeta: {
    color: '#cbd5e1',
    fontSize: 12,
    lineHeight: 18,
  },
});
